export const FILE_UPLOADING = "FILE_UPLOADING";
export const FILE_UPLOADING_SUCCESS = "FILE_UPLOADING_SUCCESS";
export const FILE_UPLOADING_FAIL = "FILE_UPLOADING_FAIL";

export const FILE_VALIDATING = "FILE_VALIDATING";
export const FILE_VALIDATING_SUCCESS = "FILE_VALIDATING_SUCCESS";
export const FILE_VALIDATING_FAIL = "FILE_VALIDATING_FAIL";

export const SET_WARNING = "SET_WARNING";
